---
openapi: 3.0.0
info:
  title: Inventory API
  description: This is a inventory API that makes calls from various vendor APIs.
  version: v1.72.1
paths:  
  "/track":
    servers:
      - url: https://alpine.com/api/inventory
    get:
      operationId: Get Inventory information
      parameters:
      - name: catalogID
        required: true
        in: query
        schema:
          example: 900000106
          type: integer
          format: int
      requestBody:
        content: {}
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/unifiedInventoryResponse'

components:
  schemas:
    unifiedInventoryResponse:
      type: object
      additionalProperties: true
      required:
      - ID
      - Title
      - Category
      - Price
      - Quantity
      - Image
      properties:
        ID:
          example: 1
          type: number
        Title:
          example: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops'
          type: string
        Quantity:
          example: '105504'
          type: string
        Category:
          example: 'men's clothing'
          type: string
        Price:
          example: 109.95
          type: number
        Image:
          example: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg'
          type: string
